import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
 /* const { data, error } = useSWR('/index', fetcher)
  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>*/

  return (
    <div className='container'>
      <Head>
        <title>Geosat Test</title>
        <meta name="description" content="Generated by create next app / dahurtadop" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className='title'>
          Bienvenido a <a href="http://geosat.com.co/"> Geosat Test!</a>
        </h1>

        <p className='description'>
          Desarrollado por {' '}
          <code className='code'>David Hurtado</code>
        </p>

        <div className='grid'>
          <Link href="/owners-info">
            <a className='card'>
              <h2>Gestionar Propietarios &rarr;</h2>
              <p>Encuentra las opciones para Consultar Crear, Actualizar y Eliminar Propietarios </p>
            </a>
          </Link>

          <Link href="/lands">
            <a className='card'>
              <h2>Gestionar Predios &rarr;</h2>
              <p>Encuentra las opciones para Consultar Crear, Actualizar y Eliminar Predios </p>
            </a>
          </Link>

          <Link href="/grounds">
            <a className='card'>
              <h2>Gestionar Territorios &rarr;</h2>
              <p>Encuentra las opciones para Consultar Crear, Actualizar y Eliminar Territorios </p>
            </a>
          </Link>

          <Link href="/buildings">
            <a className='card'>
              <h2>Gestionar Construcciones &rarr;</h2>
              <p>Encuentra las opciones para Consultar Crear, Actualizar y Eliminar Construcciones </p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
